#!/usr/bin/php
<?php
/**
 * Executable for the hook tests.
 * @category   Tests
 * @package    Main
 * @subpackage Core
 * @author     Alexander Zimmermann <alexander.zimmermann@twt.de>
 * @copyright  2008-2009 Alexander Zimmermann <alexander.zimmermann@twt.de>
 * @license    http://www.opensource.org/licenses/bsd-license.php  BSD License
 * @version    SVN: $Id: svnlook 175 2010-02-27 23:38:58Z alexander $
 * @link       http://www.azimmermann.com/
 * @since      File available since Release 1.0.0
 */

/**
	Die Kontrolle der Parameter faellt weg, da dieses Script nur fuer die
	Testumgebung verwendet wird.
*/

$aCommands = array(
			  'changed', 'diff', 'info', 'cat'
			 );

$sPath    = $argv[0];
$sCommand = $argv[1];
$sParam   = $argv[2];
$sNumber  = $argv[3];
$sRepos   = $argv[4];

$sCatFile = '';
if (true === isset($argv[5]))
{
	$sCatFile = $argv[5];
} // if


if (in_array($sCommand, $aCommands) === false)
{
	exit;
} // if

// Pfad zu _files Verzeichnis
$sPath  = str_replace('svn/svnlook', '', $sPath);
$sPath .= '../_files/';

// Datei ermitteln.
$sCatFile = basename($sCatFile);

if ($sParam === '-t')
{
	$sType = 'txn';
} // if

if ($sParam === '-r')
{
	$sType = 'rev';
} // if

// Datei fuer SVN Fake zusammenschruaben.
$sFile = $sPath . $sType . '/' . $sNumber . '/';

// Bei "cat" wird die Datei dran gehaengt.
if ($sCommand === 'cat')
{
	$sFile .= $sCatFile;
}
else
{
	$sFile .= $sCommand;
} // if

$sFile .= '.txt';

echo file_get_contents($sFile);
