#!/bin/sh
#
# An example hook script to check the commit log message taken by
# applypatch from an e-mail message.
#
# The hook should exit with non-zero status after issuing an
# appropriate message if it wants to stop the commit.  The hook is
# allowed to edit the commit message file.
#
# To enable this hook, rename this file to "applypatch-msg".

echo "RUN applypatch-msg" >> /home/alexander/Projekte/ExampleGit/hook.log

msg=${1+"$@"}
repository=$(git rev-parse --show-toplevel)

/path/to/hookframework/Hook $repository $msg client.applypath-msg >&2 || exit 1

exit 0