#!/bin/sh
#
# After the entire commit process is completed, the post-commit hook runs.
# It doesn’t take any parameters, but you can easily get the last commit by
# running git log -1 HEAD.
# Generally, this script is used for notification or something similar.

against=$(git rev-parse --verify HEAD)

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

repository=$(git rev-parse --show-toplevel)

/path/to/hookframework/Hook $repository $against client.post-commit >&2 || exit 1

exit 0